### ISSUE TITLE
Extension disables bookmarking in Chrome 41

### ISSUE THREAD

**Issue by MethodGrab** [mrflix/dimensions#19] opened 2015-03-05 13:42 UTC
As of Chrome 41 (_Chrome 41.0.2272.76 x64_, _OSX 10.10.1_), having the extension enabled prevents new bookmarks from being added. Neither `CMD+D`, the star icon in the address bar or the `Bookmarks` menu work.

**Comment by mrflix** [comment] 2015-03-09 15:07
Hey Nick. Thanks for reporting this bug. Looks like you're not alone. [@lady_stinson](https://twitter.com/lady_stinson/status/573065462113812481) reported the same bug via twitter. The bug might be connected to [this bug](https://code.google.com/p/chromium/issues/detail?id=463752&q=bookmark%20extension&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified) filled with the chromium project.

**Comment by collinb** [comment] 2015-03-17 13:22
Having the same problem.  I bookmark more than I measure so this extension will be disabled until fixed.  -Please let us know!

**Comment by augbog** [comment] 2015-03-17 22:07
:+1: Also having this problem. For some reason the address bar star wasn't working for me either until I removed Dimensions.

**Comment by MethodGrab** [comment] 2015-03-18 09:01
This is weird, I downloaded the source from `github:master` and installed it as an unpacked extension and bookmarks work fine! The Chrome Store version is still broken (Chrome _41.0.2272.89_).

**Comment by Ashwell** [comment] 2015-03-21 01:03
As a temporary fix for me I have resorted to grabbing the document or lock icon on the left of the URL in the address bar and dragging it into the bookmarks bar.

**Comment by tobiashm** [comment] 2015-04-19 13:07
@mrflix I think the issue is actually fixed here: https://github.com/mrflix/dimensions/commit/fd4b2a68269fb6f01187bec5b8858b63f238e47a#diff-2ccaee6c5cfa6c1e0a36166894df97bc since the extension then no longer conflicts with the bookmark key combo.
But you need to update the version in the web-store; it's currently 1.0.3 from 2014-09-12, where it still uses Cmd+D

**Comment by mrflix** [comment] 2015-04-19 13:11
Thank you tobias for figuring this out!
I just didn't want to publish the most recent version yet because there is still a big bug hidden somewhere which makes it unable to measure dimensions sometimes (I think it has to do with dimensions already running in one tab – that it bugs in another tab).

**Comment by SamHasler** [comment] 2015-06-02 09:41
@mrflix: Is there an issue for that bug I could subscribe to? If not could you add one with the help wanted label?

**Comment by addedlovely** [comment] 2015-07-09 11:10
@mrflix Hey Felix any news on this, we loved Dimensions and its now unusable. Would be happy to sponsor the next release if you can find some time to update.

**Comment by mrflix** [comment] 2015-07-09 11:21
@SamHasler I opened https://github.com/mrflix/dimensions/issues/23 and will actively work on this now.

@addedlovely thanks for the nudge, will continue my work now.

**Comment by mrflix** [comment] 2015-07-19 14:12
Fixed in version 2.

**Closed by mrflix** 2015-07-19 14:12 UTC

**Comment by SamHasler** [comment] 2015-07-23 14:09
:thumbsup:

**Comment by MethodGrab** [comment] 2015-07-27 12:57
:+1: thanks @mrflix!
